import React, { useEffect, useMemo, useState } from 'react';

const labels = { processando: 'Processando', concluido: 'Concluído', erro: 'Com erro' };
const PAGE_SIZE = 10;
const auditLabel = item => item.audit?.status === 'ok' ? 'Sem alertas' : item.audit?.status === 'review_required' ? 'Revisão necessária' : '—';

export function SavedExtractions({ onOpen, onResume, onBack }) {
  const [items, setItems] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [status, setStatus] = useState('todos'); const [page, setPage] = useState(1);
  const load = async () => { setLoading(true); try { const response = await fetch('/api/transcricoes'); if (!response.ok) throw new Error('Não foi possível carregar as extrações salvas.'); const data = await response.json(); setItems(data.items || []); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => items.filter(item => (status === 'todos' || item.status === status) && (item.fileName || item.id).toLowerCase().includes(query.trim().toLowerCase())), [items, query, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const currentPage = Math.min(page, pageCount); const visible = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  useEffect(() => { setPage(1); }, [query, status]);
  const remove = async item => { if (!window.confirm(`Excluir “${item.fileName || item.id}”? Esta ação remove o PDF e os dados salvos.`)) return; const response = await fetch(`/api/transcricoes/${item.id}`, { method: 'DELETE' }); if (!response.ok) return setError('Não foi possível excluir a extração.'); await load(); };
  const completed = items.filter(item => item.status === 'concluido').length; const pending = items.filter(item => item.status === 'processando').length; const failed = items.filter(item => item.status === 'erro').length;
  return <section className="saved-page"><header className="saved-header"><div><p className="eyebrow">Biblioteca</p><h1>Extrações salvas</h1><p>Consulte, retome ou exclua documentos processados.</p></div><button className="btn-success" onClick={onBack}>Nova extração</button></header>
    <div className="saved-stats"><div><span>Total</span><strong>{items.length}</strong></div><div><span>Concluídas</span><strong>{completed}</strong></div><div><span>Processando</span><strong>{pending}</strong></div><div><span>Com erro</span><strong>{failed}</strong></div></div>
    <div className="saved-toolbar"><label className="saved-search"><span className="sr-only">Buscar extrações</span><input placeholder="Buscar por arquivo ou código..." value={query} onChange={event => setQuery(event.target.value)} /></label><label className="saved-filter"><span>Status</span><select value={status} onChange={event => setStatus(event.target.value)}><option value="todos">Todos</option><option value="concluido">Concluídas</option><option value="processando">Processando</option><option value="erro">Com erro</option></select></label></div>
    {error && <p className="login-error-alert">{error}</p>}
    <div className="saved-table-wrap">{loading ? <p className="saved-empty">Carregando extrações…</p> : visible.length === 0 ? <p className="saved-empty">Nenhuma extração encontrada com estes filtros.</p> : <table className="saved-table"><thead><tr><th>Documento</th><th>Status</th><th>Auditoria</th><th>Progresso</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><strong>{item.fileName || 'Documento sem nome'}</strong><small>#{item.id}</small></td><td><span className={`status-pill ${item.status}`}>{labels[item.status] || item.status}</span></td><td>{auditLabel(item)}</td><td>{item.progress?.percentage || 0}%</td><td>{item.updatedAt ? new Date(item.updatedAt).toLocaleString('pt-BR') : '—'}</td><td><div className="saved-actions">{item.status === 'concluido' ? <button className="btn-secondary" onClick={() => onOpen(item)}>Abrir</button> : <button className="btn-success" onClick={() => onResume(item)}>Retomar</button>}<button className="btn-danger" onClick={() => remove(item)}>Excluir</button></div></td></tr>)}</tbody></table>}</div>
    {!loading && filtered.length > 0 && <footer className="pagination"><span>Mostrando {(currentPage - 1) * PAGE_SIZE + 1}–{Math.min(currentPage * PAGE_SIZE, filtered.length)} de {filtered.length}</span><div><button className="btn-secondary" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Anterior</button><span>Página {currentPage} de {pageCount}</span><button className="btn-secondary" disabled={currentPage === pageCount} onClick={() => setPage(currentPage + 1)}>Próxima</button></div></footer>}
  </section>;
}
