import React, { useEffect, useState } from 'react';
import { UploadZone } from './components/UploadZone.jsx'; import { PdfViewer } from './components/PdfViewer.jsx'; import { EditableTable } from './components/EditableTable.jsx'; import { ExportBar } from './components/ExportBar.jsx'; import { TranscriptionProgress } from './components/TranscriptionProgress.jsx'; import { LoginForm } from './components/LoginForm.jsx'; import { SavedExtractions } from './components/SavedExtractions.jsx'; import { Sidebar } from './components/Sidebar.jsx';
async function readJsonResponse(response, fallbackMessage) { try { const data = await response.json(); return data; } catch { throw new Error(fallbackMessage); } }
export default function App() {
  const [auth, setAuth] = useState({ loading: true, enabled: false, authenticated: false }); const [uploadedFile, setUploadedFile] = useState(null); const [jobId, setJobId] = useState(null); const [jobStatus, setJobStatus] = useState('idle'); const [jobProgress, setJobProgress] = useState(null); const [extractedData, setExtractedData] = useState(null); const [errorMessage, setErrorMessage] = useState(''); const [screen, setScreen] = useState('main'); const [savedPdfUrl, setSavedPdfUrl] = useState('');
  useEffect(() => { fetch('/api/auth/session').then(response => response.json()).then(data => setAuth({ loading: false, ...data })).catch(() => setAuth({ loading: false, enabled: true, authenticated: false })); }, []);
  useEffect(() => { if (!auth.authenticated || !jobId || jobStatus !== 'processando') return; const interval = setInterval(async () => { try { const res = await fetch(`/api/transcricoes/${jobId}`); if (!res.ok) throw new Error('Falha ao consultar status da transcrição.'); const data = await readJsonResponse(res, 'O servidor retornou uma resposta inválida.'); if (data.progress) setJobProgress(data.progress); if (data.status === 'concluido') { setExtractedData(data.value); setJobStatus('concluido'); clearInterval(interval); } else if (data.status === 'erro') { setErrorMessage(data.erro || 'Falha ao processar documento.'); setJobStatus('erro'); clearInterval(interval); } } catch (err) { setErrorMessage(err.message); setJobStatus('erro'); clearInterval(interval); } }, 500); return () => clearInterval(interval); }, [auth.authenticated, jobId, jobStatus]);
  const reset = () => { setUploadedFile(null); setJobId(null); setJobStatus('idle'); setJobProgress(null); setExtractedData(null); setErrorMessage(''); setSavedPdfUrl(''); setScreen('main'); };
  const upload = async file => { setUploadedFile(file); setJobStatus('processando'); setJobProgress({ current: 0, total: 0, percentage: 0, message: 'Enviando arquivo ao servidor...', logs: [] }); setErrorMessage(''); setExtractedData(null); try { const form = new FormData(); form.append('arquivo', file); form.append('tipo', 'holerite'); const response = await fetch('/api/transcricoes', { method: 'POST', body: form }); const data = await readJsonResponse(response, 'O servidor não conseguiu receber o arquivo.'); if (!response.ok) throw new Error(data.erro || 'Erro ao enviar arquivo.'); setJobId(data.id); } catch (err) { setErrorMessage(err.message); setJobStatus('erro'); } };
  const save = async () => { const response = await fetch(`/api/transcricoes/${jobId}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ value: extractedData }) }); if (!response.ok) { const data = await readJsonResponse(response, 'Não foi possível salvar.'); throw new Error(data.erro); } };
  const open = async item => { const response = await fetch(`/api/transcricoes/${item.id}`); if (!response.ok) return setErrorMessage('Não foi possível abrir a auditoria.'); const data = await response.json(); setJobId(data.id); setExtractedData(data.value); setUploadedFile(null); setSavedPdfUrl(`/api/transcricoes/${item.id}/arquivo`); setJobStatus(data.status); setScreen('main'); };
  const resume = async item => { const response = await fetch(`/api/transcricoes/${item.id}/retomar`, { method: 'POST' }); if (!response.ok) return setErrorMessage('Não foi possível retomar a auditoria.'); const data = await response.json(); setJobId(data.id); setUploadedFile(null); setSavedPdfUrl(`/api/transcricoes/${item.id}/arquivo`); setJobStatus('processando'); setScreen('main'); };
  const logout = () => fetch('/api/auth/logout', { method: 'POST' }).finally(() => { setAuth({ loading: false, enabled: true, authenticated: false }); reset(); });
  if (auth.loading) return null; if (auth.enabled && !auth.authenticated) return <LoginForm onLoginSuccess={() => setAuth({ loading: false, enabled: true, authenticated: true })} />;
  return <div className="workspace"><Sidebar screen={screen} onNavigate={next => next === 'main' ? reset() : setScreen(next)} onLogout={logout} /><main className="container">{screen === 'saved' ? <SavedExtractions onOpen={open} onResume={resume} onBack={reset} /> : <>{jobStatus === 'idle' && <UploadZone onUpload={upload} isProcessing={false} />}{jobStatus === 'processando' && <TranscriptionProgress file={uploadedFile} progress={jobProgress} />}{jobStatus === 'erro' && <div className="upload-card"><h2>Erro na Transcrição</h2><p>{errorMessage}</p><button className="btn-secondary" onClick={reset}>Tentar novamente</button></div>}{jobStatus === 'concluido' && <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}><div className="split-view"><PdfViewer file={uploadedFile} pdfUrl={savedPdfUrl} /><EditableTable data={extractedData} onChangeData={setExtractedData} /></div><ExportBar jobId={jobId} onSave={save} onReset={reset} /></div>}</>}</main></div>;
}
